### ISSUE TITLE
Allow getting current scroll

### ISSUE THREAD

**Issue by LoganDark** [NeekSandhu/react-aspen#16]
I'm trying to implement a drag and drop thing but in order to do that I need to calculate which item the cursor is dragging over. I can't do that without knowing the scroll position of the tree view, which right now requires poking at private fields that I honestly don't even really have access to (due to the FileTree itself being buried down a bit). Could you add an API for getting the current scroll position of the tree view?

`container.firstElementChild!.firstElementChild!.scrollTop` is kind of jank

**Comment by LoganDark** [comment]
Yes, I think it uses dragover events or something - which isn't possible, because flexlayout overlays a transparent element over the entire app while you're dragging.

**Comment by NeekSandhu** [comment]
https://neeksandhu.github.io/aspen-tree-model/classes/treestatemanager.html#scrolloffset

**Comment by NeekSandhu** [comment]
See also - TreeStateWatcher if you need live reporting on scroll offset

**Comment by LoganDark** [comment]
What about changing scroll offset? i.e. scrolling tree view when your cursor is near the bottom or top

**Comment by NeekSandhu** [comment]
I think complex behaviours like the one you describe should be left for the end users to accommodate as there can't be a one-size-fits all solution. Your case is a perfect example - the transparent layer on top.

UI events are a tricky business anyway. `preventDefault`, `stopPropagation` and whatnot.

**Comment by LoganDark** [comment]
> I think complex behaviours like the one you describe should be left for the end users to accommodate

I'm an end user trying to accommodate this and I have no idea how scrolling should be done. Should I just go and set `container.firstElementChild!.firstElementChild!.scrollTop`?

**Comment by NeekSandhu** [comment]
That's a fair argument. For now use the hacky method that you tried to set the offset. Please open a new issue regarding the ability to set the scroll offset in a nice way.
